[project]
name = "repl-nix-ecofootprintmapper"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "branca>=0.8.0",
    "folium>=0.18.0",
    "geopy>=2.4.1",
    "plotly>=5.24.1",
    "streamlit-folium>=0.23.1",
    "streamlit>=1.40.0",
]
